name: przepisnik_v3
description: Przepisnik 3-gen
publish_to: 'none'
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_database: ^10.0.8
  firebase_core: ^2.4.0
  provider: ^6.0.5
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_displaymode: ^0.6.0
  flutter_slidable: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.1.0
  google_fonts: ^5.1.0
  styled_widget: ^0.4.1
  flutter_login: ^4.1.1
  share_plus: ^7.0.2
  rxdart: ^0.27.7
  reactive_forms: ^16.0.1
  flutter_svg: ^2.0.7
  flutter_colorpicker: ^1.0.3
  smooth_corner: ^1.1.0
  scaled_list: ^2.0.0
  flutter_quill: ^7.2.18
  animations: ^2.0.7
  flutter_snake_navigationbar: ^0.6.1
  get: ^4.6.5
  carbon_icons: ^0.0.1+2
  cloud_firestore: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/category_icons/
    - assets/system_icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#     - family: PrzepisnikIcons
#       fonts:
#         - asset: fonts/PrzepisnikIcons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
